import streamlit as st
import os
import glob
from google import genai
from google.genai import types
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from app.agent import root_agent

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

st.set_page_config(page_title="Autonomous Data Scientist Agent", layout="wide")

st.title("🤖 Autonomous Data Scientist Agent")
st.markdown("Upload your dataset, specify an optional target variable, and let ADSA perform complete end-to-end Machine Learning profiling and modeling.")

# 1. File Upload & Settings
with st.sidebar:
    st.header("1. Upload Dataset")
    uploaded_file = st.file_uploader("Choose a CSV or Parquet file", type=['csv', 'parquet'])
    
    st.header("2. Settings")
    target_variable = st.text_input("Target Variable (Optional)", help="Leave blank for ADSA to heuristically detect the target.")
    
    run_btn = st.button("Run Full Pipeline", type="primary")

# 2. Pipeline Execution
if run_btn and uploaded_file is not None:
    # Save the file
    os.makedirs("datasets", exist_ok=True)
    file_path = os.path.join("datasets", uploaded_file.name)
    with open(file_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
        
    st.session_state["dataset_path"] = file_path
    
    # Run the pipeline directly in Python via ADK Runner
    prompt = file_path
    if target_variable:
        prompt = f"{file_path} --target {target_variable}"
        
    with st.spinner("Analyzing data, testing models, and generating report... This may take a minute or two."):
        try:
            session_service = InMemorySessionService()
            session = session_service.create_session_sync(user_id="streamlit_user", app_name="adsa")
            runner = Runner(agent=root_agent, session_service=session_service, app_name="adsa")
            message = types.Content(role="user", parts=[types.Part.from_text(text=prompt)])
            
            # Execute the workflow DAG directly in memory (no HTTP timeout!)
            events = list(runner.run(new_message=message, user_id="streamlit_user", session_id=session.id))
            
            st.success("Pipeline complete!")
            st.session_state["pipeline_run"] = True
        except Exception as e:
            st.error("Pipeline failed!")
            st.exception(e)

# 3. Display Report and Charts
if st.session_state.get("pipeline_run", False):
    report_path = "outputs/final_report.md"
    
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.subheader("📋 Final Report")
        if os.path.exists(report_path):
            with open(report_path, "r") as f:
                report_content = f.read()
            st.markdown(report_content)
        else:
            st.warning("Report not found.")
            
    with col2:
        st.subheader("📊 Interactive Visualizations")
        html_files = glob.glob("outputs/*.html")
        png_files = glob.glob("outputs/*.png")
        
        # Display Images (like SHAP)
        for img in png_files:
            st.image(img, caption=os.path.basename(img))
            
        # Display HTML widgets
        for html_file in html_files:
            with st.expander(f"View {os.path.basename(html_file)}"):
                with open(html_file, "r") as f:
                    html_data = f.read()
                st.components.v1.html(html_data, height=500, scrolling=True)

# 4. Conversational Chat Interface
st.divider()
st.subheader("💬 Discuss the Findings")

if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat messages from history on app rerun
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# Accept user input
if prompt := st.chat_input("Ask a question about the report..."):
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": prompt})
    
    # Display user message in chat message container
    with st.chat_message("user"):
        st.markdown(prompt)
        
    # Read the report to inject as context
    report_context = ""
    if os.path.exists("outputs/final_report.md"):
        with open("outputs/final_report.md", "r") as f:
            report_context = f.read()

    # Generate assistant response
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        
        client = genai.Client()
        
        # Build history for the API
        contents = [
            types.Content(
                role="user", 
                parts=[types.Part.from_text(f"Here is the data science report generated by the pipeline:\n\n{report_context}\n\nAnswer the user's questions based primarily on this report.")]
            ),
            types.Content(role="model", parts=[types.Part.from_text("Understood. I will answer any questions based on the provided report.")])
        ]
        
        for msg in st.session_state.messages:
            contents.append(
                types.Content(role=msg["role"], parts=[types.Part.from_text(msg["content"])])
            )
            
        response_stream = client.models.generate_content_stream(
            model='gemini-2.5-flash',
            contents=contents
        )
        
        full_response = ""
        for chunk in response_stream:
            full_response += chunk.text
            message_placeholder.markdown(full_response + "▌")
            
        message_placeholder.markdown(full_response)
        
    # Add assistant response to chat history
    st.session_state.messages.append({"role": "model", "content": full_response})
